### ISSUE TITLE
Doesn't detect AC networks

### ISSUE THREAD

**Issue by EionRobb** [acalcutt/Vistumbler#1]
Hi there,

Wireless-AC networks just show up as 802.11 instead of 802.11ac which is how they show in the netsh command.

I tried looking for where the netsh command is parsed to see if it was just looking for one letter after the 802.11, but couldn't see where that code lives.

**Comment by EionRobb** [comment]
Did the change from https://github.com/acalcutt/Vistumbler/issues/1#issuecomment-49105539 make its way in?  Was the commit just not tagging this issue?

**Comment by acalcutt** [comment]
it made its way in long ago, but this was never closed

**Comment by acalcutt** [comment]
Just FYI, this looks like the commit it was added in.  https://github.com/acalcutt/Vistumbler/commit/ffb146620ff91f7292d6ee5e45cad91b01ba38fb#diff-04ff4e5936d2dd46946ec9a3d42e8955e1239cfbd7d2e4184dd9df1ca95eb5d6
