### ISSUE TITLE
Malware reported in Windows 10 Trojan:Script/Woreflint.A!cl  and Program:Win32/Ymacco.AAEC

### ISSUE THREAD

**Issue by shamitv** [acalcutt/Vistumbler#7]
Windows 10 now flags Vistumbler zip / installers : 

![image](https://user-images.githubusercontent.com/8604949/109783337-e6a7dd00-7c2f-11eb-945b-cc11441f9e94.png)

![image](https://user-images.githubusercontent.com/8604949/109783474-0b9c5000-7c30-11eb-9fda-d94a79b84afa.png)

**Comment by aha999** [comment]
Good thing i saw this issue. something shady going on ? Scanned with Malwarebytes:
![slika](https://user-images.githubusercontent.com/50620416/110543813-11f86380-812b-11eb-8d57-bba90937a033.png)

**Comment by acalcutt** [comment]
I have sent the following false positive submission to microsoft

here are the submissions
https://www.microsoft.com/en-us/wdsi/submission/f073ed0e-b9b7-44a8-83de-49be808f789e
https://www.microsoft.com/en-us/wdsi/submission/263b7cb1-76f4-40a2-b93f-341d86de5c44

Hopefully they find these just to be false positives (which I get with
every new release)

**Comment by acalcutt** [comment]
Looks like microsoft has removed the detection on those two files

vistumbler_v10-7.exe

Submission ID: f073ed0e-b9b7-44a8-83de-49be808f789e

Status: Completed

Submitted by: acalcutt@worcester.edu

Submitted: Mar 9, 2021 6:43:09 PM

User Opinion: Incorrect detection

Analyst comments:

We have removed the detection. Please follow the steps below to clear
cached detection and obtain the latest malware definitions. 1. Open command
prompt as administrator and change directory to c:\Program Files\Windows
Defender 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures” 3. Run
"MpCmdRun.exe -SignatureUpdate" Alternatively, the latest definition is
available for download here:
https://www.microsoft.com/en-us/wdsi/definitions Thank you for contacting
Microsoft.
Click here for more information

vistumbler_v10-7_portable.zip

Submission ID: 263b7cb1-76f4-40a2-b93f-341d86de5c44

Status: Completed

Submitted by: acalcutt@worcester.edu

Submitted: Mar 9, 2021 6:50:28 PM

User Opinion: Incorrect detection

Analyst comments:

We have removed the detection. Please follow the steps below to clear
cached detection and obtain the latest malware definitions. 1. Open command
prompt as administrator and change directory to c:\Program Files\Windows
Defender 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures” 3. Run
"MpCmdRun.exe -SignatureUpdate" Alternatively, the latest definition is
available for download here:
https://www.microsoft.com/en-us/wdsi/definitions Thank you for contacting
Microsoft.
Click here for more information
